### ISSUE TITLE
Info about how to enable ssh access in the wiki

### ISSUE THREAD

**Issue by cmarmo** [Unicamp-OpenPower/minicloud#1]
Hello,
first of all thanks to Unicamp for providing the OpenPower minicloud service... it saves me a lot of panic in looking around for power platforms!

This is just a suggestion about the wiki, more than a real issue.
I am more a reading person than a watching video one, and I couldn't find in the 'Getting Started' page any info about the fact that ssh access must be enabled after the creation of the virtual machine.... After a day of 'Connection timed out' and ssh key checking I finally decided to watch the video and this solved my problem ... :)
So, thanks for the video... :)
Maybe one line more in the wiki about that could be useful?

Thanks for reading me,
Chiara

**Comment by Igortorrente** [comment]
Thanks for your report, we fixed this issue on getting started tutorial.
