### ISSUE TITLE
minicloud not responding to admin commands

### ISSUE THREAD

**Issue by aschuh703** [Unicamp-OpenPower/minicloud#12]
I have logged into the minicloud admin webpage. I had previously (5 days ago) created an instance then shut it down. Today, I tried to start it and the status remained at shut off. I then tried to delete the instance. Once again, the webpage says deleting and never stops.

I don't mind creating a new instance, but I am getting no where.

**Comment by inconstante** [comment]
I have the same problem, but I got stuck at a hard reboot.

**Comment by inconstante** [comment]
I deleted the old instance and recreated it from a **new** image (Debian 10), and now the web interface (including access to the VNC console) is a lot more responsive.  I have no idea why.

**Comment by lcnzg** [comment]
@gftg85 Sorry, I had to restart our unstable node. We have not yet discovered the cause of the problem.
If this problem continues, we will reinstall the node.

**Comment by shawnl** [comment]
Same problem. My VM does not boot in its default set-up, and if I can't interrupt the boot I run into this problem, and it makes it very hard to start my VM successfully.

**Comment by lcnzg** [comment]
Sorry for all the problems. We had to reinstall the unstable node, so hopefully everything will go well now.
If any problem happen, let us know!
