### ISSUE TITLE
Overview of available resources?

### ISSUE THREAD

**Issue by AEI-SXSmirror** [Unicamp-OpenPower/minicloud#14]
Not a bug, rather a wishlist item:

I seem to be unable to find out about available resources, so if I overshoot and create an instance bigger than what's currently available, I fail.
I'd like to adjust my request (in a responsible manner) to less than the amount of available resources. Some information would be required for that.

Did I just miss the overall-status page?

**Comment by lcnzg** [comment]
I just created instances and had no problems.
Could you provide the size of the instance used, the availability zone chosen and the error?

**Comment by AEI-SteffenG** [comment]
I was running a tiny instance (1 core, 16 GB /) but doing some complex compiles required more than 3 GB of virtual memory. Adding more swap didn't help. 
I therefore attempted to launch another instance (medium, IIRC) but that one didn't start, and there was only a "Start failed" error message. (Any power8/9)
I'm now starting a large instance, based on the snapshot I took from the tiny one, and this time it's spawning - I still cannot see whether there are any resources left (and how many).
So while it seems to work this time the whole thing can fail again next time.
BTW, (this may be a FAQ): can I switch back to the tiny vm later without snapshotting?

**Comment by steve8x8** [comment]
It seems that unavailable resources are flagged in the "Flavor" step of instance creation ("above your quota"). Since the Details, Source and Flavor stages can be filled in in random order, it seems best to start with Flavor to find what's available and what isn't. Not optimal, but feasible. Thanks.

**Comment by lcnzg** [comment]
If you go to Project -> Compute -> Overview, you can review the resources available to your account.

![image](https://user-images.githubusercontent.com/24390439/64929850-833eab00-d801-11e9-98ad-cb739f2254eb.png)
