### ISSUE TITLE
Do you have a backup of the instance that was deleted?

### ISSUE THREAD

**Issue by shawnl** [Unicamp-OpenPower/minicloud#17]
It looks like my main instance was deleted, as well as the snapshot that I had from a while ago. Do you have a back-up of this? There is some important work on libnss that was on there that I do not have a back-up of.

**Comment by shawnl** [comment]
Just found where the snapshots are, that should be enough.

**Comment by lcnzg** [comment]
Sorry, but we lost a few instances in the last maintenance and we had no backup for them
