### ISSUE TITLE
SMT?

### ISSUE THREAD

**Issue by AEI-SXSmirror** [Unicamp-OpenPower/minicloud#18]
Not a bug, just a question: is it possible to get SMT enabled so there can be two (or even more) threads per physical core?

**Comment by ALutz273** [comment]
[fedora@xxxxx~]$ ppc64_cpu --smt
Machine is not SMT capable

**Comment by AEI-SteffenG** [comment]
Does this command exist in Debian? (Which package?)

In any case, this response comes too late since I long lost access to the test machine, and I should have closed the ticket months ago...

**Comment by ALutz273** [comment]
on debian is the package **powerpc-ibm-utils-1.3.7-1**
