### ISSUE TITLE
Remote ipython kernel in spyder/jupyter 

### ISSUE THREAD

**Issue by albertosaa** [Unicamp-OpenPower/minicloud#23]
The use of remote ipython kernel in spyder or jupyter requires access to some ports that seem to be unavailable to users in the minicould environment. Is there any workaround for this?

**Comment by lcnzg** [comment]
You can use SSH Port Forwarding (https://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html).

```
ssh -L LOCAL_PORT:localhost:REMOTE_PORT VM_USER@minicloud.parqtec.unicamp.br
```

Or add the tag `LocalForward LOCAL_PORT localhost:REMOTE_PORT` to your `.ssh/config` file

More information on how to use SSH forwarding with Spyder IDE: https://medium.com/@mazzine.r/how-to-connect-your-spyder-ide-to-an-external-ipython-kernel-with-ssh-putty-tunnel-e1c679e44154

**Comment by albertosaa** [comment]
Many thanks, Luciano, for the quick and accurate reply.

 It works!

![image](https://user-images.githubusercontent.com/30988872/71123366-392ee200-21c1-11ea-9455-32bb29b067cc.png)
