### ISSUE TITLE
My loggin is not working.

### ISSUE THREAD

**Issue by hugoziviani** [Unicamp-OpenPower/minicloud#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hugoziviani** [comment]
Hello guys, how's it going? Thanks for the service... I would like to know about my loggin.  My user is hugo.zivini and I can't access my account. There is anything I can do? Thanks a lot.

**Comment by lcnzg** [comment]
You need to request a new account. Due to an OpenStack upgrade, all accounts have been removed.

**Comment by hugoziviani** [comment]
Good. Thanks, Hugs.
