### ISSUE TITLE
No big-endian PPC image available

### ISSUE THREAD

**Issue by jkivilin** [Unicamp-OpenPower/minicloud#25]
**Describe the bug**
There is no longer any big-endian image available in Minicloud. I'd would need to test out endian-correctness and performance delta between both endianness in PPC assembly implementations.

**To Reproduce**
1. Go to 'Launch Instance / Source'
2. All current images are little-endian, 'ppc64le'.

**Expected behavior**
It would be nice to have at least one 'ppc64be/ppc64' image.

**Comment by lcnzg** [comment]
I just added the following ppc64 images: Fedora 27, Fedora 28 and openSUSE Tumbleweed.

**Comment by jkivilin** [comment]
Thanks!
