### ISSUE TITLE
Strange SSH incompatibility in key format ?

### ISSUE THREAD

**Issue by wtarreau** [Unicamp-OpenPower/minicloud#27]
**Describe the bug**

I tried to set up a key pair from one of my keys and failed to get in, with the publickey authentication always being rejected. So I created a new keypair directly in the interface, trashed the machine and created a new one with that keypair (is there any way to test a key without trashing an instance each time?), and it also fails, as can be seen in ssh -v below.

debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: Will attempt key: wtap-minicloud.pem  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: wtap-minicloud.pem
sign_and_send_pubkey: no mutual signature supported
debug1: No more authentication methods to try.
ubuntu@minicloud.parqtec.unicamp.br: Permission denied (publickey).

**To Reproduce**
simply try to connect over SSH. I'm pretty sure that not everyone is affected and that it looks like an algorithm incompatibility. But given that the keys created in the interface also don't work, I'm a bit at lost.

Here's my version:
$ ssh -V
OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018

Any hint appreciated :-)

Thanks!
Willy

**Comment by wtarreau** [comment]
I finally found an older machine to test from and there it works using the same key:
```
$ ssh -V
OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
```
Thus I suspect that the problem might be caused by some of the algos recently removed from SSH (probably DSA here), while the minicloud interface doesn't accept the newer ED25519 keys.

So it's likely that the issue will increase over time as SSH clients are upgraded in field.

Since I can access the machine now, I'm fine if you want to close the bug. But I'm letting it open so that you guys have a chance to see it in case you want to know.

**Comment by sitio-couto** [comment]
See issue [#32 ](https://github.com/Unicamp-OpenPower/minicloud/issues/32).
