### ISSUE TITLE
FreeBSD disk image

### ISSUE THREAD

**Issue by adalava** [Unicamp-OpenPower/minicloud#28]
I made an experimental FreeBSD 13 disk image for POWER and uploaded it as a "community" image so my colleagues could also use it and help with test. 

The problem is that it's not appearing for my colleagues, even searching for the exact name. The image name is "FreeBSD13-head-r359311".

Also, feel free to make it available to everyone if you wish. If security is a concern, I can send instructions on how to create it from scratch downloading the artifacts from FreeBSD build servers.

**Comment by rpsene** [comment]
@adalava I will upload it and make it public.

**Comment by adalava** [comment]
@rpsene awesome, thanks!

**Comment by adalava** [comment]
After reading #25, I would like to note that FreeBSD 13 is a Big Endian image as well. FreeBSD only supports BE currently.

**Comment by rpsene** [comment]
@jr-santos98 could you handle it? Grab the image, make it public via our OpenStack.

**Comment by jr-santos98** [comment]
@adalava @rpsene the following image: "FreeBSD13-head-r359311". It was defined as public at Minicloud.

**Comment by adalava** [comment]
@jr-santos98 the image visibility didn't change for me, then I deleted it to see if the public one would appear, but it was not the case.
Anyway, please put this on hold a little bit, this one has limited number of free inodes, limiting the number of files that can be written to the filesystem. My patch is under review by FreeBSD team and a new image will be generated soon.

**Comment by jr-santos98** [comment]
@adalava Probably to you it might not seem like a publisher, but surely the other people at Minicloud would be able to access it. I am waiting for the next image, and in the next one, try to confirm with other people if it is available.

**Comment by adalava** [comment]
Hi @jr-santos98. New image is available with name "FreeBSD13-head-r359571"
It's currently set as "Shared". Thanks!

Latest images can also be grabbed from https://artifact.ci.freebsd.org/snapshot/head/latest/powerpc/powerpc64/disk.qcow2.zst

**Comment by jr-santos98** [comment]
@adalava the following image: "FreeBSD13-head-r359571". It was defined as public at Minicloud.

**Comment by adalava** [comment]
Thank you @jr-santos98, I see the image set as public and it's working fine!

I see there's is another public image with the name "FreeBSD 13 ppc64" and ID "53fcc845-c013-4051-b086-46c303295810". This one is pretty old, doesn't work out of the box and can deleted.

**Comment by jr-santos98** [comment]
@adalava Thanks for the feedback. When removing the image: "FreeBSD 13 ppc64", I will take the idea to the other team members.

**Comment by martin-frbg** [comment]
Does this image need any specific hardware provisions (e.g. something bigger than minicloud.small) ? I cannot get it to boot beyond a "HV-RTAS-BOOTUP error -4" in the log while Linux images come on line just fine.

**Comment by adalava** [comment]
Hi @martin-frbg , I just tested the image on a new minicloud.tiny instance (1vCPU, 1GB of RAM, 20GB of disk) and it worked out of the box, on the "Power8" availability zone. 
Are you using it on Power9? I didn't had the chance to try on it yet since my account doesn't have access to it. I'll ask for an upgrade.

**Comment by martin-frbg** [comment]
No I'm on Power8, currently with a minicloud.small instance (2 vCPU). Just tried a soft reboot but still cannot ssh into it, and the Instance Console Log in the web interface again stops at the HV-RTAS-BOOTUP error.

**Comment by adalava** [comment]
@martin-frbg, that's strange, I tried minicloud.small as well and it worked. I don't expect SSH to be working right away because on this image you have to configure network and configure sshd to permit root login, but you should see it booting in the console.
@jr-santos98 or @rpsene, could you please check if there are differences in the "minicloud.small" template used by @martin-frbg other than the number of vCPUs ?

Here are screenshots for reference:
https://pasteboard.co/J3OJawT.png
https://pasteboard.co/J3OJNS2.png

**Comment by martin-frbg** [comment]
Ah, alright - I had originally assumed them to be completely usable but I guess there is no easy way to label them as experimental on the site. I'll just blow it away and retry with a minicloud.tiny instance then (BTW I now see that the HV-RTAS message is the same in the logs of fully working instances, the difference is just that there is no output beyond that. 
EDIT : I suddenly do get the VNC console now (which did not work earlier) so I'll try to get everything set up from there. 
Thank you very much for your work on this image!

**Comment by jr-santos98** [comment]
@martin-frbg There were two images from FreeBSD. One was already a little old and as was requested in this issue, it was removed. The other, which was just posted, is public and functioning normally. I recommend using "FreeBSD13-head-r359571". Any questions I ask you to return to this issue or consult the documents of Miniclound or FreeBSD.

**Comment by martin-frbg** [comment]
@jr-santos98 that would explain why the older FreeBSD image was still selectable in the interface but failed to find a vdisk on bootup. Unfortunately the new r359571 image has no networking configured at all and I am not sure I know enough about your setup to do it myself (apart from being a bit rusty on pure BSD file locations and command options)

**Comment by adalava** [comment]
@martin-frbg I'm glad it booted! The FreeBSD 12.1 release doesn't work on the minicloud. The FreeBSD 13 that is being shared on the minicloud isn't a final release, it's still under active development so this image is meant for development and testing. 
If you find any problem, feel free to get in touch (alfredo  _at_  freebsd.org) or contact other FreeBSD developers through maillist and IRC.

I've just added some Minicloud-scpecific instructions at https://wiki.freebsd.org/powerpc/QEMU#UNICAMP_OpenPower_Minicloud

It currently has instructions to setup network and grow the filesystem.
I hope you have fun and let me know if you have any problem!

**Comment by adalava** [comment]
@jr-santos98, thank you for providing the image! 
I think this issue can be closed now.
