### ISSUE TITLE
virtio-drivers supported by FreeBSD

### ISSUE THREAD

**Issue by adalava** [Unicamp-OpenPower/minicloud#3]
Hi,

I'm currently using the experimental flavor "minicloud.HugePages-BSD" but the device "virtio-block" that is expose by minicloud isn't currently working with FreeBSD virtio drivers.
Would be possible to replace virtio-block by virtio-scsi? (or leave both so it can used to investigate the issue)

Thanks,
Alfredo

**Comment by rpsene** [comment]
@Igortorrente could you please take a look on how to create a new flavor with that driver?

**Comment by Igortorrente** [comment]
@adalava You only need add hw_scsi_model=virtio-scsi and hw_disk_bus=scsi at image metadata. Project -> compute -> <your image> -> dropdown menu -> update metadata -> custom.

**Comment by adalava** [comment]
@Igortorrente , it works fine for me! 
Just a note: it didn't work if I update the instance metadata, but I updated the image metadata and created a new instance and worked fine.
