### ISSUE TITLE
Newspeak

### ISSUE THREAD

**Issue by shawnl** [Unicamp-OpenPower/minicloud#30]
**Describe the bug**

  |   |   |   |   |  
-- | -- | -- | -- | -- | --
 
  |   |  
 
Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP |   |   |   | Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP | Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP
  |   |  
Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP | Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP
Hello, 													 													Your account has been renewed. We are available for any problems.  													Please use the Report an Issue section, informing the quota size that you need, and we will evaluate your request.   													 													Sincerely, 													OpenPOWER@UNICAMP

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rpsene** [comment]
@shawnl could you elaborate more what you are reporting?

**Comment by shawnl** [comment]
I am asking for an account.

**Comment by rpsene** [comment]
@shawnl go to https://openpower.ic.unicamp.br/minicloud/ and select Request Access. Here we only handle issues :)

**Comment by shawnl** [comment]
As you can see above, I did so, and the answer was that my account was reenabled (it was not), and that I should ask here with the specs I need. You can see why I am confused.

**Comment by rpsene** [comment]
@shawnl please, ask again for a new account.

**Comment by shawnl** [comment]
I need a permanent account in order to do my work. I had one initially, and now you keep playing with me, including not following the very policies you tell me about.

**Comment by sitio-couto** [comment]
Hey @shawnl,
I assume this is about the email sent on Friday, May 29th, notifying that your account was about to expire. Is this correct? 
If so, please, disregard that email, your account won't be deactivated again.
If not, could you elaborate on what is the issue you're having? As it appears to us, the account is enabled and working normally.
