### ISSUE TITLE
Acesso ao Minicloud

### ISSUE THREAD

**Issue by FernandoALima** [Unicamp-OpenPower/minicloud#33]
Estou preenchendo o formulário Doc (https://forms.gle/9Yf2RkG7ES24JURR7) para solicitar o acesso ao Minicloud, mas quando eu submeto, ele informa que eu tenho de informar a justificativa, mesmo já preenchido o campo.
"We are curious, tell us more about your intentions :)"
Meu e-mail: fernandoantonio.lima@gmail.com

**Comment by jr-santos98** [comment]
@FernandoALima é preciso que o seu requets tenha umas duas linhas. Então, fala um pouco mais sobre o seu pedido. Será com base na sua resposta, que iremos decidir se liberamos ou não o acesso a Minicloud.
