### ISSUE TITLE
Certificate of the https://minicloud.parqtec.unicamp.br/ page was revoked

### ISSUE THREAD

**Issue by doodeck** [Unicamp-OpenPower/minicloud#34]
**Describe the bug**

You are not able to reach the login page https://minicloud.parqtec.unicamp.br/. The message is similar to this:

This website’s security certificate has been revoked, so you can’t go there at this time. 
Error Code: ERROR_INTERNET_SEC_CERT_REVOKED

**To Reproduce**
Open the web page https://minicloud.parqtec.unicamp.br/ in your favourite web browser.

**Expected behavior**
Access to control panel.

**Comment by jr-santos98** [comment]
Hello @doodeck ,
Try to open the site through the anonymous tab. If the error is resolved, clear your browser's cookies and caches.
If it doesn't, try using other browsers like Mozilla Firefox.

**Comment by doodeck** [comment]
Firefox works, thanks.
