### ISSUE TITLE
server certificate revoked

### ISSUE THREAD

**Issue by dsysko** [Unicamp-OpenPower/minicloud#35]
**Describe the bug**
After my access was granted, I received a login link in my email. 
When clicking on it I got a certificate security error from my browser.

**To Reproduce**
1. Go to '[Login button from email](https://minicloud.parqtec.unicamp.br/horizon/)'
2. See error:
> minicloud.parqtec.unicamp.br normally uses encryption to protect your information. When Vivaldi tried to connect to minicloud.parqtec.unicamp.br this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be minicloud.parqtec.unicamp.br, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Vivaldi stopped the connection before any data was exchanged.
> 
> You cannot visit minicloud.parqtec.unicamp.br right now because its certificate has been revoked. Network errors and attacks are usually temporary, so this page will probably work later.

**Expected behavior**
A login screen to input my temporary credentials

**Additional context**
I am connecting from the USA

**Comment by rpsene** [comment]
@dsysko it is working properly now.
