### ISSUE TITLE
Firmware outdate

### ISSUE THREAD

**Issue by ravanelli** [Unicamp-OpenPower/minicloud#36]
It is not actually a bug. However, I couldn't find other place to request it.

The Power 8 server I'm using (IP: 10.8.41.53), looks to have an outdate firmware, each is missing some patch to allow qemu/libguest to run.

I'm getting:
qemu-system-ppc64: Requested count cache flush assist capability level not supported by KVM
According to https://bugzilla.redhat.com/show_bug.cgi?id=1768551, it could be fixed updating the firmware.

Would be possible to get this firmware update?

**Comment by jr-santos98** [comment]
In addition to github, you can contact us through the channel [gitter](https://gitter.im/Unicamp-OpenPower/Lobby) or email: openpower@ic.unicamp.br

We're already underway with a full minicloud update.

**Comment by ravanelli** [comment]
@jr-santos98 Thanks for the info ;) 
This firmware update is blocking us to work with Power, would be possible to get that update? Since it is more related to HW stuff. I can help in the process if you have questions in how to do it.

**Comment by jr-santos98** [comment]
@ravanelli We will check for firmware update availability on Friday, September 3rd. That way, as soon as we carry out this operation, I will inform you of the result.

**Comment by ravanelli** [comment]
@jr-santos98 Thanks for the update! I appreciate your help.

**Comment by jr-santos98** [comment]
Hello @ravanelli , 
We found that the machines are some outdated Firmware versions. The update will take place over the next week. I'll let you know as soon as we perform the update.

**Comment by jr-santos98** [comment]
Hello @ravanelli ,
Sorry for the delay to answer.
The firmware of the servers were updated, all of them already have the latest version.

**Comment by ravanelli** [comment]
Hi @jr-santos98 Thanks for updating it.
