### ISSUE TITLE
console access not working

### ISSUE THREAD

**Issue by carenas** [Unicamp-OpenPower/minicloud#39]
**Describe the bug**
After launching several different machines in different OS and types, hadn't been able to access their console (which for the freebsd one is a blocker, as it doesn't have network/ssh access AFAIK)

**To Reproduce**
1. Launch an instance and wait for it to be deployed and running
2. Click on its name and select log to confirm the system has initialized (FreeBSD won't show a login prompt, but that is just likely a console misconfiguration)
3. Select console
4. No Console shows; if clicking the link to show it in a full window it will result in a network timeout trying to connect to minicloud.parqtec.unicamp.br:6080/vnc_auto.html?...

**Expected behavior**
Console should be shown, or at least the http connection shouldn't fail and hopefully it could be reachable by a vnc client (even if it runs in the browser)

**Comment by carenas** [comment]
alternatively (at least for using the FreeBSD image), a new one that configures the network and it is otherwise setup by cloud_init like the others could be provided, but that would require that uploading images be enabled (at least for my account) so I can help with that.

**Comment by jr-santos98** [comment]
@carenas thanks for report.
We are updating our network, so some features are being blocked accidentally.
Console access has been unlocked.

**Comment by carenas** [comment]
thanks for working on it so late into the weekend

**Comment by carenas** [comment]
@jr-santos98: FWIW the instance (now shutdown) in :

  https://minicloud.parqtec.unicamp.br/horizon/project/instances/057f2047-4c3f-41ff-bb19-4cc4126161cc/

is upgraded to FreeBSD 13.1RC1 and configured to be cloud ready (including setting the freebsd user with the right key and resizing the root disk), so if an image could be made out of that the lack of a console wouldn't block any other FreeBSD tester.

I did create an snapshot of it but it was quickly deleted, so I couldn't test it independendly and didn't hear about enabling image uploading so can't provide a simpler option, but hopefully making an snapshot and truncating it should be easy enough.

**Comment by jr-santos98** [comment]
@carenas I'm creating a FreeBSD image.
When i create it, I'll let you know here.

**Comment by jr-santos98** [comment]
@carenas I'm not getting to create a snapshot and not even unlock the instance.
Can you unlock the instance and create a snapshot ??
If you can, send me the name of snapshot.

**Comment by carenas** [comment]
@jr-santos98: sorry for the delay; it also has git installed, but should be otherwise as close as a base image as possible.

Name
FreeBSD-13.1RC1
ID
44958b3c-72f7-48a7-ab2d-af8ec8f16834

**Comment by carenas** [comment]
in case a smaller image without git would work better :

Name: fbsdbase
ID: 4060ff90-d166-4ee4-a166-dcf96d3b7dec

and that corresponds to the instance 14a96b51-30da-4e65-9e85-573c3bab3c99, which I will keep shutdown and should be ready to be configured by cloud-init and to expand its root fs in the next boot.
