### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by hugoziviani** [Unicamp-OpenPower/minicloud#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hugoziviani** [comment]
Hello guys, there is some modification I can make to get more time in SSH session? My connections are closing very quickly.

**Comment by lcnzg** [comment]
Hello, can you try the steps described in this link? https://bjornjohansen.no/ssh-timeout

**Comment by hugoziviani** [comment]
Thanks a lot!
