### ISSUE TITLE
Cannot delete a personal ISO

### ISSUE THREAD

**Issue by adalava** [Unicamp-OpenPower/minicloud#5]
I uploaded a ISO image called "FreeBSD 13 ELFV2 good" and marked it as "protected", by mistake.
Now I can't delete this image since "Delete" option doesn't appear for this image. I'm asking the sysadmin to delete it for me.

Thanks!

**Comment by lcnzg** [comment]
I think you can edit your image details and set Protected to No. But I already deleted it, anyway.
