### ISSUE TITLE
need a little additional quota for a Big-Endian VPS

### ISSUE THREAD

**Issue by shawnl** [Unicamp-OpenPower/minicloud#7]
**Describe the bug**
I needed the MAX size VPS for building LLVM, but now I can't have a Big-Endian server for testing big-endian and 32-bit PPC.

**To Reproduce**
1. add a maximum sized vps
2. can't add more

I can't actually see the instances size, but the smallest big-endian instance would be fine. I don't even need the 10GB ram that the max instance has.

But I couldn't test on big-endian which made my patch buggy when i guessed here:
https://sourceware.org/ml/libc-alpha/2019-07/msg00139.html

**Comment by lcnzg** [comment]
More quota added. Can you verify if it worked?

**Comment by shawnl** [comment]
worked thank you
