### ISSUE TITLE
Can't access instance

### ISSUE THREAD

**Issue by shawnl** [Unicamp-OpenPower/minicloud#8]
**Describe the bug**
My main instance "big-daddy", debian ppc64le with ip 10.8.40.133, seems to be stuck in a reboot loop. I can't stop it, and it never starts. It was acting flaky and disconnecting ssh until i tried to reboot it. (I was also briefly out of disk space on it, if that makes any difference)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shawnl** [comment]
OK, I'm still having serious reliability problems. Can you try to look into the issues?

**Comment by lcnzg** [comment]
I confirm there is a problem with our Power9 load. I am working on this.

**Comment by shawnl** [comment]
seems to be resolved.

**Comment by shawnl** [comment]
> Failed to terminate process 65544 with SIGKILL: Device or resource busy

I am wondering if maybe the stability problems were low disk space.

**Comment by lcnzg** [comment]
Can you test again?

**Comment by shawnl** [comment]
The current kernel I have set to boot (Debian's 5.2 in sid) doesn't boot, and the console window just spins until its too late (and the VNC key changes each reboot).
